logging:
    file: /var/log/swoutcall/${spring.application.name}.log 
    config: classpath:logback-spring.xml
    level:
        root: INFO
        org.springframework: INFO
        com.lige: INFO
        
